# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: 0.4.0
_src_path: gh:radio-aktywne/template-database-minio
accountname: radio-aktywne
databasename: medialounge
description: Emission prerecordings media 🛋️
docs: true
docsurl: https://radio-aktywne.github.io/database-medialounge
envprefix: MEDIALOUNGE
imagename: databases/medialounge
port: 29000
registry: true
releases: true
reponame: database-medialounge
repourl: https://github.com/radio-aktywne/database-medialounge
webport: 29001
